#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me
sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html

otherdefault="/etc/nginx/sites-enabled/default"
location="\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=fHI8X4OXluQ;\n\t}\n"
sudo sed -i "30i $location" "$otherdefault"
sudo service nginx restar
