#!/usr/bin/env bash
# Script that installs Nginx server and redirects
sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html
str="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$str/" /etc/nginx/sites-available/default
sudo service nginx restart
