#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sed -i '/server_name _;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=kPRA0W1kECg&ab_channel=TimoBingmann  permanent;' /etc/nginx/sites-available/default
service nginx start
