#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y install haproxy

str_haproxy="frontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 646-web-01 34.139.211.56:80 check\n\tserver 646-web-02 3.215.22.101:80 check"
echo -e "$str_haproxy" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
