#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get update
sudo apt-get -y install haproxy

sudo sed -i -e '$ afrontend http_front \n\tbind *:80 \
\tmode http \
\tdefault_backend http_rear \
\nbackend http_rear \
\tbalance		roundrobin \
\tserver 646-web-01		34.139.211.56  check \
\tserver 646-web-02		3.215.22.101 check' /etc/haproxy/haproxy.cfg

sudo service haproxy restart
