#!/usr/bin/env bash
#Process and PID file
file=/var/run/myscript.pid
sudo touch -- "$file"
sudo bash -c 'echo $$ > /var/run/holbertonscript.pid'

trap 'sudo m -f /var/run/holbertonscript.pid' SIGQUIT SIGTERM
trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINT

while 'true'; do
	echo "To infinity and beyond"
	sleep 2
done
exit 0

