#!/usr/bin/env bash
#Process and PID file
file=/var/run/myscript.pid
sudo touch -- "$file"
sudo bash -c 'echo $$ > /var/run/holbertonscript.pid'

trap 'sudo m -f /var/run/holbertonscript.pid; exit' SIGQUIT
trap 'echo "I hate the kill command sudo rm /var/run/holbertonscript.pid"; exit' SIGTERM
trap "echo Y U no love me?!" SIGINT

while 'true'; do
	echo "To infinity and beyond"
	sleep 2
done
exit 0
