#!/usr/bin/env bash
#bash script that displays: The content of the current directory

for files in *;
do
	if [[ -d $files ]];
	then
		echo "$files"
	elif [[ -f $files ]];
	then
		echo "$files"
	else
		exit 1
	fi
done
