#!/usr/bin/env bash
# ening on port 80 of all the server’s active IPv4 IPs
sed -i "/listen 8080 default_server;/listen 80 default_server;/" /etc/nginx/sites-enabled/default
sed -i "/listen \[::\]:8080 default_server ipv6only=on;/listen \[::\]:80 default_server;/" /etc/nginx/sites-enabled/default
sed -i "/ ipv6only=on//" /etc/nginx/sites-available/default
service nginx restart
